/**
 * Writes TMJ vs committed-gram SVG renders and a browsable index.html under
 * `<repo>/artifacts/parity-gallery/` for CI artifact upload (see workflow).
 */
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { gramPathToRenderModel } from "../test/render/gram-adapter.js";
import { tmjPathToRenderModel } from "../test/render/tmj-adapter.js";
import { renderSvg } from "../test/render/svg-renderer.js";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = dirname(scriptDir);
const repoRoot = join(packageRoot, "..", "..");
const sandboxDir = join(repoRoot, "maps", "sandbox");
const outDir = join(repoRoot, "artifacts", "parity-gallery");

function escHtml(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

async function main(): Promise<void> {
  mkdirSync(outDir, { recursive: true });

  const stems = readdirSync(sandboxDir)
    .filter((f) => f.endsWith(".tmj"))
    .map((f) => f.replace(/\.tmj$/i, ""))
    .sort();

  const navItems: string[] = [];
  const sections: string[] = [];

  for (const stem of stems) {
    const tmjPath = join(sandboxDir, `${stem}.tmj`);
    const gramPath = join(sandboxDir, `${stem}.map.gram`);
    if (!existsSync(gramPath)) {
      console.warn(`[parity-gallery] skip ${stem}: missing ${stem}.map.gram`);
      continue;
    }

    const tmjModel = await tmjPathToRenderModel(tmjPath);
    const gramModel = await gramPathToRenderModel(gramPath, tmjModel.frame);
    const svgTmj = renderSvg(tmjModel);
    const svgGram = renderSvg(gramModel);

    const fileTmj = `${stem}-tmj.svg`;
    const fileGram = `${stem}-gram.svg`;
    writeFileSync(join(outDir, fileTmj), svgTmj, "utf8");
    writeFileSync(join(outDir, fileGram), svgGram, "utf8");

    navItems.push(`<li><a href="#${escHtml(stem)}">${escHtml(stem)}</a></li>`);
    sections.push(`<section class="map-block" id="${escHtml(stem)}">
  <h2>${escHtml(stem)}</h2>
  <div class="pair">
    <div class="pane">
      <h3>TMJ source</h3>
      <object class="svg-frame" data="${escHtml(fileTmj)}" type="image/svg+xml" title="${escHtml(stem)} TMJ"></object>
    </div>
    <div class="pane">
      <h3>Committed <code>.map.gram</code></h3>
      <object class="svg-frame" data="${escHtml(fileGram)}" type="image/svg+xml" title="${escHtml(stem)} gram"></object>
    </div>
  </div>
</section>`);
  }

  if (sections.length === 0) {
    console.warn("[parity-gallery] no map pairs found; wrote empty index only");
  }

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>TMJ vs gram — parity gallery</title>
  <style>
    :root { font-family: system-ui, sans-serif; line-height: 1.4; }
    body { margin: 0 auto; max-width: 1400px; padding: 1rem 1.5rem 3rem; color: #1a1a1a; }
    h1 { font-size: 1.35rem; margin-top: 0; }
    nav ul { margin: 0.5rem 0 1.5rem; padding-left: 1.25rem; }
    .map-block { margin-bottom: 2.5rem; padding-top: 0.5rem; border-top: 1px solid #ddd; }
    .map-block h2 { font-size: 1.1rem; margin: 0.75rem 0 0.5rem; }
    .pair {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 1rem;
      align-items: start;
    }
    @media (max-width: 900px) { .pair { grid-template-columns: 1fr; } }
    .pane h3 { font-size: 0.95rem; margin: 0 0 0.35rem; font-weight: 600; }
    .pane code { font-size: 0.85em; }
    .svg-frame {
      display: block;
      width: 100%;
      min-height: 200px;
      border: 1px solid #bbb;
      border-radius: 4px;
      background: #fafafa;
    }
    .note { font-size: 0.85rem; color: #444; margin-bottom: 1rem; }
  </style>
</head>
<body>
  <h1>TMJ vs committed gram (SVG)</h1>
  <p class="note">Generated by <code>pnpm --filter @aie-matrix/tmj-to-gram run gallery:parity</code>.
    Flat fills match Layer 3 parity geometry (see <code>test/render/svg-renderer.ts</code>).</p>
  <nav><strong>Maps</strong><ul>
    ${navItems.join("\n    ")}
  </ul></nav>
  ${sections.join("\n  ")}
</body>
</html>
`;

  writeFileSync(join(outDir, "index.html"), html, "utf8");

  writeFileSync(
    join(outDir, "README.txt"),
    [
      "TMJ vs gram parity gallery (CI artifact)",
      "",
      "1. Unzip this folder",
      "2. Open index.html in a browser (local file:// is OK)",
      "3. SVGs load as sibling files via <object> — keep files in the same directory",
      "",
      `Generated maps: ${sections.length}`,
      "",
    ].join("\n"),
    "utf8",
  );

  console.log(`[parity-gallery] wrote ${sections.length} map pair(s) to ${outDir}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
